### ISSUE TITLE
Cannot help new schools login

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#148]
![login](https://cloud.githubusercontent.com/assets/5199620/2572186/06cf15c0-b910-11e3-885c-2eb043bd5973.png)

Her email is saying that it does not exist but that is the email I have for her?

**Comment by brittanyukulele** [comment]
Hi Brittany! we are Carolina Feican, Josemaria Mardonez, Natalia Fiallo and Claudia Ocampo. Caroline helped me with your email adress. We are really excited to start a new trade scohol in our city (Cuenca-Ecuador) and we have already been working on some important things in order to start one. Four weeks ago we finally filled out the form in the tradeschool website but we havent received any answer or technical support yet. Please let us know something about the situation. Thank you very much!

**Comment by brittanyukulele** [comment]
I am having this issue with everyone I am trying to get in the site: including danielwichers@gmail.com

**Comment by RachL** [comment]
Hi @brittanyukulele ! A feedback from my side: I have trouble to connect Caroline from TS Bordeaux. Same problem you've mentioned.
She is the one who has sent the TS opening request. As a temporary solution and from the TS Bordeaux admin panel, I've added Annabelle (another TS Bordeaux team member) to the organizers with the creation of a new profile. And she can log in easily (no error message).

Maybe, while the bug is being fixed, this could be a way for new people to log in. Tell me if my explanation was clear. Btw I've also tried to change the email address for Caroline through the backend and it didn't work either...

**Comment by brittanyukulele** [comment]
Hi! I have had success with changing the email address too. No idea why doing that works, but that's the best I got. :)

**Comment by dnephin** [comment]
I've got a quick fix and some explanation of what is happening in #154

**Comment by dnephin** [comment]
Hello everyone. Or has been quiet for the the last month or so, and I don't have permission to merge these  pull requests. I have 4 pending, one to add calendars and the other 3 are bug fixes.

Do you feel comfortable merging them, or do you when when Or might be back to have a look and merge them?

Thanks!

**Comment by brittanyukulele** [comment]
If this is directed at me, let me know how I can help. Also, welcome and nice to meet you! I am unsure how/what to merge?

Thanks!

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy http://twitter.com/tradeschoolindy 
(317) 366-6938

http://tradeschool.coop/Indianapolis http://tradeschool.coop/Indianapolis/class

**Comment by orzubalsky** [comment]
New organizers should be able to log in now. We could still experience issues with recent organizers that were added to the system. 

You can verify that the organizer is active in the system by looking at the organizers page in the admin section and checking to see that the "is active" field is checked (thank you Daniel for that).

If there are other problems with individual people please email me with the username. Thanks!
