### ISSUE TITLE
quantities of barter

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#157]
hey team!
i know i had spoken to or about this, but i can't remember if we could make this optional or not. we would really like to be able to add quantities of the barter item that the teacher would like so it will not be a choosable item once three people have selected it. that would help us a lot with teachers not ending up going home with ten packages of coffee and one of the other things. let me know your thoughts. thank you!!!

**Comment by RachL** [comment]
Hi @brittanyukulele I agree: this feature would be really great. Another example that happen to us: if there is something like "bring your smile/good mood", most of the participants are checking this item and no other item on the list.... Which is a bit disappointing for the teacher...

**Comment by michellesoto** [comment]
Hey @RachL and @brittanyukulele, 

This has has been a recurrent request/complain that we've had from teachers at Quito TS (La Trueca). It would be great to be able to put a limit in the quantities of the barter items. We have experienced both the issue of everyone signing up for the "Bring your smile" or that teachers end up getting a lot of just one item. We don't have anyone here that knows how to use python in order to fix this.. any ideas on how we could make it happen? I wonder if this is an issue that other tradeschools have experienced?

cheers, 

Michelle
