### ISSUE TITLE
Time & Barter Items Class Registration

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#68]
"My name is Amy Finke & I recently signed up for my first Trade School Indy class, which was Intro To HTML on Wednesday, Feb. 12 at 6:30PM. Since I thought this class may be beneficial to my sister, I went ahead & signed her up as well. When I clicked to "Join" & filled out the required information, I noticed at the top that it said it was going to be held from 11:30PM to 1AM instead."

I noticed in the info section of the class, it now has the barter items? Is that something we can edit? Photo attached. In the same photo, the time is also different than the actual time of the class. It says 10:30pm to 12am?
![screenshot 7](https://f.cloud.github.com/assets/5199620/2010621/3ca08d72-8770-11e3-8fbf-fc1a90868311.png)
![screenshot 6](https://f.cloud.github.com/assets/5199620/2010623/3dca9a94-8770-11e3-8f4b-c42b09fb7132.png)

**Comment by orzubalsky** [comment]
Good catch with the time bug! This is happening because the data in the popup with the class information is not being filled with the correct timezone. I'll let you know here when it's fixed.

Changing the way the class html element looks is a separate issue, and probably not a bug :) If you want to remove that information or change the way it looks, follow these steps:
1. Login to the admin backend and click on "edit HTML templates".
2. Edit the file indianapolis/course_item.html
3. Look at line 51-53 where it says "block course_items".
4. Delete line 52, where it says {{ block.super }}
5. Click on save.

Let me know if you have any questions!

**Comment by orzubalsky** [comment]
Hey, did setting the timezone change these times as well?

**Comment by brittanyukulele** [comment]
It did. It went back to the messed up times.

**Comment by orzubalsky** [comment]
Fixing #81 fixed this as well.
