### ISSUE TITLE
Deleting Organizers

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#72]
Giving me '403 Forbidden'

**Comment by orzubalsky** [comment]
This is not a bug, it's the expected behavior. I think we shouldn't delete organizers since they might be working with other schools. Instead, you can remove an organizer from your school by going to http://tradeschool.coop/admin/tradeschool/branch, selecting an organizer on the right (under "chosen organizers") and clicking on the arrow pointing left to move them to available organizers. Don't forget to hit save when you're done.
