### ISSUE TITLE
Adding branches to admin user

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#93]
How do I add other branches to my profile so I can switch between them when I am logged in? I can't find the right place to add them...
- question
- low priority

**Comment by orzubalsky** [comment]
I reversed the way this happens so now a school would a person instead of someone just adding themselves to any school. can you write the list of schools and I'll add you?

from now on, when you help set up a school you should just be able to see them in the admin section (or you can always ask them to add you in the organizers section of branches)

**Comment by laurabillings** [comment]
Please can you add me to...

London
Westminster
West Norwood
Norwich
Willesden
Croydon
Tulse Hill
Hackney
Wrens Nest
Barbican

Phew!

On Fri, Jan 31, 2014 at 11:49 PM, or zubalsky notifications@github.comwrote:

> I reversed the way this happens so now a school would a person instead of
> someone just adding themselves to any school. can you write the list of
> schools and I'll add you?
> 
> from now on, when you help set up a school you should just be able to see
> them in the admin section (or you can always ask them to add you in the
> organizers section of branches)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/93#issuecomment-33854556
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by orzubalsky** [comment]
Thanks, they should all be there now :)
